#! /bin/sh

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2020> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#   Copyright <2020> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                                 #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# #########################
# ####    PNX v1.0.     ###
# #########################

_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }


# -- Set PNX directories.

PNX_ROOT="/home/.pnx"
PNX_CACHE="/var/lib/pacman"
PNX_KEYRINGS="/usr/share/pacman/keyrings"


# -- Flags for the command.

case "$1" in

	-h|--help)

		echo "Welcome to PNX!"
		echo "Description:"
		echo "    PNX is a wrapper for Pacman. Pacman is a package management utility that tracks installed packages on a Linux system."
		echo "    This wrapper allows the user to use Pacman on a Linux distribution that is not a derivative of Arch Linux without conflicts with"
		echo "    the distribution existing package manager."
		echo "    Report bugs at: https://github.com/Nitrux/pnx."
		echo "Flags:"
		echo "    --initialize, Create PNX root directory."
		echo "    --key, Use pacman-key: pacman-key - manage pacman's list of trusted keys."
		echo "    --repo, Use repo-add: repo-add - package database maintenance utility."
		echo "    --launch, Launch a program installed using PNX."
		echo "    --remove-dirs, Remove PNX directories."
		echo "    --debug, Run PNX with debug on."
		echo "    --release, Show the version."
		echo "Usage:"
		echo "    When no flag is specified, PNX will default to package management."
		echo "        pnx <operation> [options] [targets]"
		echo "        pnx <flag> <operation> [options] [targets]"
		echo "Examples:"
		echo "sudo pnx -S inkscape"
		echo "    To install a package using PNX use the same syntax as Pacman."
		echo "    For example, pnx -S inkscape will download and install inkscape and all the packages it depends on."
		echo "sudo pnx -Syu"
		echo "    Update package list and upgrade all packages afterwards."
		echo "sudo pnx --key --init"
		echo "    Ensure the keyring is properly initialized and has the required access permissions."
		echo "sudo pnx --repo --verify"
		echo "    Verify the PGP signature of the database before updating the database."
		echo "pnx --launch inkscape"
		echo "    This will execute a program installed using PNX."
		exit

	;;

	--launch)

		export \
			PATH=$PNX_ROOT/usr/bin/:$PNX_ROOT/usr/sbin/:$PNX_ROOT/usr/games/:$PNX_ROOT/bin/:$PNX_ROOT/sbin/ \
			LD_LIBRARY_PATH=$PNX_ROOT/usr/lib/:$PNX_ROOT/usr/lib/i386-linux-gnu/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/:$PNX_ROOT/usr/lib32/:$PNX_ROOT/usr/lib64/:$PNX_ROOT/lib/:$PNX_ROOT/lib/i386-linux-gnu/:$PNX_ROOT/lib/x86_64-linux-gnu/:$PNX_ROOT/lib32/:$PNX_ROOT/lib64/:$PNX_ROOT/usr/lib/dri/:$PNX_ROOT/usr/lib/pulseaudio/:$PNX_ROOT/usr/lib/gdk-pixbuf-2.0/:$PNX_ROOT/gs-plugins-13/:$PNX_ROOT/usr/lib/systemd/:$PNX_ROOT/usr/lib/samba/:$PNX_ROOT/usr/lib/girepository-1.0/:$PNX_ROOT/usr/lib/WebKitNetworkProcess/:$PNX_ROOT/usr/lib/epiphany/:$PNX_ROOT/usr/lib/opera/:$PNX_ROOT/usr/lib/firefox/ \
			XDG_DATA_DIRS=$PNX_ROOT/usr/share/ \
			GSETTINGS_SCHEMA_DIR=$PNX_ROOT/usr/share/glib-2.0/schemas/ \
			QT_PLUGIN_PATH=$PNX_ROOT/usr/lib/qt4/plugins/:$PNX_ROOT/usr/lib/i386-linux-gnu/qt4/plugins/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/qt4/plugins/:$PNX_ROOT/usr/lib32/qt4/plugins/:$PNX_ROOT/usr/lib64/qt4/plugins/:$PNX_ROOT/usr/lib/qt5/plugins/:$PNX_ROOT/usr/lib/i386-linux-gnu/qt5/plugins/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/qt5/plugins/:$PNX_ROOT/usr/lib32/qt5/plugins/:$PNX_ROOT/usr/lib64/qt5/plugins/
			TERM=xterm-256color \
			GTK_PATH=$PNX_ROOT/usr/lib/:$PNX_ROOT/lib:$PNX_ROOT/lib64 \

		shift && "$@"
		exit $?

	;;

	--release)

		echo "${0##*/}: version 1.0, 14th January 2020."
		echo "The license used for this file and its contents is: BSD-3-Clause."
		echo "Authors:"
		echo "    Copyright <2020> <Uri Herrera <uri_herrera@nxos.org>>"
		echo "    Copyright <2020> <Luis Lavaire <luis_lavaire@nxos.org>>"
		echo "Made with ♥ by Nitrux Latinoamericana S.C."
		exit

	;;

esac


#	Probe for PNX root existence.

test -d $PNX_ROOT ||
	_e "${0##*/} has not been initialized. Please run: sudo ${0##*/} --initialize."


#	Require root for the following operations.

test $(id -u) -ne 0 &&
	_e "Please run ${0##*/} as root. Try with: sudo ${0##*/}."
­

case "$1" in

	--initialize)

		test \
			-d $PNX_ROOT \
			-a -d $PNX_CACHE \
			-a -d $PNX_KEYRINGS &&
		_e "Already initialized."

		mkdir -p $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS
		cp -a $APPDIR/usr/share/pacman/keyrings/* $PNX_KEYRINGS

		echo "Please run these commands to start using PNX:"
		echo "sudo ${0##*/} --key --init"
		echo "sudo ${0##*/} --key --populate"

	;;

	--key)

		export LIBRARY=$APPDIR/usr/share/makepkg
		pacman-key "$2"
		exit

	;;

	--repo)

		repo-add "$2"
		exit

	;;

	--remove-dirs)

		rm -R $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS
		exit

	;;

esac


#	By default use Pacman if no flag is specified.

pacman "$@"


# -- Integrate .desktop files from PNX directory into the user's directory after installing a program with Pacman.

# for dot_d in $(pacman -r $PNX_ROOT -Qql | grep '\.desktop'); do
# 	ln -sf $PNX_ROOT/$dot_d $HOME/.local/share/applications
# done
