#! /bin/sh

case "$1" in

	-h|--help)

		echo "${0##*/}: Launch a program installed with PNX."
		echo "Usage: ${0##*/} <command> [arguments]"
		exit

	;;

	-x|--debug)

		set -x
		shift

	;;

esac

_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }


# -- Configure the execution environment.

PNX_ROOT='/home/.pnx'

export \
	PATH=$PNX_ROOT/usr/bin/:$PNX_ROOT/usr/sbin/:$PNX_ROOT/usr/games/:$PNX_ROOT/bin/:$PNX_ROOT/sbin/ \
	LD_LIBRARY_PATH=$PNX_ROOT/usr/lib/:$PNX_ROOT/usr/lib/i386-linux-gnu/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/:$PNX_ROOT/usr/lib32/:$PNX_ROOT/usr/lib64/:$PNX_ROOT/lib/:$PNX_ROOT/lib/i386-linux-gnu/:$PNX_ROOT/lib/x86_64-linux-gnu/:$PNX_ROOT/lib32/:$PNX_ROOT/lib64/:$PNX_ROOT/usr/lib/dri/:$PNX_ROOT/usr/lib/pulseaudio/:$PNX_ROOT/usr/lib/gdk-pixbuf-2.0/:$PNX_ROOT/gs-plugins-13/:$PNX_ROOT/usr/lib/systemd/:$PNX_ROOT/usr/lib/samba/:$PNX_ROOT/usr/lib/girepository-1.0/:$PNX_ROOT/usr/lib/WebKitNetworkProcess/:$PNX_ROOT/usr/lib/epiphany/:$PNX_ROOT/usr/lib/opera/:$PNX_ROOT/usr/lib/firefox/ \
	XDG_DATA_DIRS=$PNX_ROOT/usr/share/ \
	GSETTINGS_SCHEMA_DIR=$PNX_ROOT/usr/share/glib-2.0/schemas/ \
	QT_PLUGIN_PATH=$PNX_ROOT/usr/lib/qt4/plugins/:$PNX_ROOT/usr/lib/i386-linux-gnu/qt4/plugins/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/qt4/plugins/:$PNX_ROOT/usr/lib32/qt4/plugins/:$PNX_ROOT/usr/lib64/qt4/plugins/:$PNX_ROOT/usr/lib/qt5/plugins/:$PNX_ROOT/usr/lib/i386-linux-gnu/qt5/plugins/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/qt5/plugins/:$PNX_ROOT/usr/lib32/qt5/plugins/:$PNX_ROOT/usr/lib64/qt5/plugins/
	TERM=xterm-256color \
	GTK_PATH=$PNX_ROOT/usr/lib/:$PNX_ROOT/lib:$PNX_ROOT/lib64 \


# -- Launch the command.

"$@"
