#! /bin/sh

#!/bin/sh

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2020> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#   Copyright <2020> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                               #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################

case "$1" in

	-h|--help)

		echo "${0##*/}: Launch a program installed with PNX."
		echo "Usage: ${0##*/} <command> [arguments]"
		exit

	;;

	-x|--debug)

		set -x
		shift

	;;

esac

_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }


# -- Configure the execution environment.

PNX_ROOT='/home/.pnx'

export \
	PATH=$PNX_ROOT/usr/bin/:$PNX_ROOT/usr/sbin/:$PNX_ROOT/usr/games/:$PNX_ROOT/bin/:$PNX_ROOT/sbin/ \
	LD_LIBRARY_PATH=$PNX_ROOT/usr/lib/:$PNX_ROOT/usr/lib/i386-linux-gnu/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/:$PNX_ROOT/usr/lib32/:$PNX_ROOT/usr/lib64/:$PNX_ROOT/lib/:$PNX_ROOT/lib/i386-linux-gnu/:$PNX_ROOT/lib/x86_64-linux-gnu/:$PNX_ROOT/lib32/:$PNX_ROOT/lib64/:$PNX_ROOT/usr/lib/dri/:$PNX_ROOT/usr/lib/pulseaudio/:$PNX_ROOT/usr/lib/gdk-pixbuf-2.0/:$PNX_ROOT/gs-plugins-13/:$PNX_ROOT/usr/lib/systemd/:$PNX_ROOT/usr/lib/samba/:$PNX_ROOT/usr/lib/girepository-1.0/:$PNX_ROOT/usr/lib/WebKitNetworkProcess/:$PNX_ROOT/usr/lib/epiphany/:$PNX_ROOT/usr/lib/opera/:$PNX_ROOT/usr/lib/firefox/ \
	XDG_DATA_DIRS=$PNX_ROOT/usr/share/ \
	GSETTINGS_SCHEMA_DIR=$PNX_ROOT/usr/share/glib-2.0/schemas/ \
	QT_PLUGIN_PATH=$PNX_ROOT/usr/lib/qt4/plugins/:$PNX_ROOT/usr/lib/i386-linux-gnu/qt4/plugins/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/qt4/plugins/:$PNX_ROOT/usr/lib32/qt4/plugins/:$PNX_ROOT/usr/lib64/qt4/plugins/:$PNX_ROOT/usr/lib/qt5/plugins/:$PNX_ROOT/usr/lib/i386-linux-gnu/qt5/plugins/:$PNX_ROOT/usr/lib/x86_64-linux-gnu/qt5/plugins/:$PNX_ROOT/usr/lib32/qt5/plugins/:$PNX_ROOT/usr/lib64/qt5/plugins/
	TERM=xterm-256color \
	GTK_PATH=$PNX_ROOT/usr/lib/:$PNX_ROOT/lib:$PNX_ROOT/lib64 \
	

# -- Launch the command.

"$@"
