#!/bin/sh

#############################################################################################################################################################################
#   The license used for this file and its contents is: BSD-3-Clause                                                                                                        #
#                                                                                                                                                                           #
#   Copyright <2020> <Uri Herrera <uri_herrera@nxos.org>>                                                                                                                   #
#   Copyright <2020> <Luis Lavaire <luis_lavaire@nxos.org>>                                                                                                               #
#                                                                                                                                                                           #
#   Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:                          #
#                                                                                                                                                                           #
#    1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.                                        #
#                                                                                                                                                                           #
#    2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer                                      #
#       in the documentation and/or other materials provided with the distribution.                                                                                         #
#                                                                                                                                                                           #
#    3. Neither the name of the copyright holder nor the names of its contributors may be used to endorse or promote products derived from this software                    #
#       without specific prior written permission.                                                                                                                          #
#                                                                                                                                                                           #
#    THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,                      #
#    THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS                  #
#    BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE                 #
#    GOODS OR SERVICES; LOSS OF USE, DATA,   OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT,                      #
#    STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.   #
#############################################################################################################################################################################


# #########################
# ####    PNX v1.0.     ###
# #########################


if [ "$EUID" -ne 0 ]
  then _e "Please run PNX as root.\nTry with: sudo ${0##*/}\n Exiting..."
  exit
fi

_e () { echo -e "${0##*/}: \e[31mError:\e[0m $@" >&2; exit 1; }


# -- Set PNX directories.

PNX_ROOT="/home/.pnx"
PNX_CACHE="/var/lib/pacman"
PNX_KEYRINGS="/usr/share/pacman/keyrings"


# -- Flags for the command.

case "$1" in

	-h|--help)

		echo "${0##*/}: Welcome to PNX!. \n"
		echo "Description: \n"
		echo "    PNX is a wrapper for Pacman. Pacman is a package management utility that tracks installed packages on a Linux system."
		echo "    This wrapper allows the user to use Pacman on a Linux distribution that is not a derivative of Arch Linux without conflicts with"
		echo "    the distribution existing package manager.  \n"
		echo "    Report bugs at: https://github.com/Nitrux/pnx. \n"
		echo "Flags: \n"
		echo "    --initialize, Create PNX root directory."
		echo "    --key, Use pacman-key: pacman-key - manage pacman's list of trusted keys."
		echo "    --repo, Use repo-add: repo-add - package database maintenance utility."
		echo "    --launch, Launch a program installed using PNX."
		echo "    --remove-dirs, Remove PNX directories."
		echo "    --debug, Run PNX with debug on."
		echo "    --release, Show the version. \n"
		echo "Usage: \n"
		echo "    When no flag is specified, PNX will default to package management."
		echo "        pnx <operation> [options] [targets]"
		echo "        pnx <flag> <operation> [options] [targets] \n"
		echo "Examples: \n"
		echo "sudo pnx -S inkscape"
		echo "    To install a package using PNX use the same syntax as Pacman."
		echo "    For example, pnx -S inkscape will download and install inkscape and all the packages it depends on."
		echo "sudo pnx -Syu"
		echo "    Update package list and upgrade all packages afterwards."
		echo "sudo pnx --key --init"
		echo "    Ensure the keyring is properly initialized and has the required access permissions."
		echo "sudo pnx --repo --verify"
		echo "    Verify the PGP signature of the database before updating the database."
		echo "pnx --launch inkscape"
		echo "    This will execute a program installed using PNX."
		echo "\n"
		exit

	;;

	--initialize)

		[ -d $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS ] && _e "${0##*/} directories already exist!.\nExiting...\n " || echo "${0##*/} directories do not exist, creating...\n\n Please run these commands to start using PNX:\n sudo ${0##*/} --key --init\n sudo ${0##*/} --key --populate\n " && mkdir -p $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS && cp -a $APPDIR/usr/share/pacman/keyrings/* $PNX_KEYRINGS
		exit

	;;

	--key)

		export \
			LIBRARY=$APPDIR/usr/share/makepkg &&
		pacman-key "$2"
		exit

	;;

	--repo)

		repo-add "$2"
		exit

	;;

	--launch)

		pnx-launch "$2"
		exit

	;;

	--remove-dirs)

		rm -R $PNX_ROOT $PNX_CACHE $PNX_KEYRINGS
		exit

	;;

	--debug)

		set -x
		shift

	;;

	--release)

		echo "${0##*/}: version 1.0, 14th January 2020.\n "
		echo "The license used for this file and its contents is: BSD-3-Clause. \n "
		echo "Authors: \n"
		echo "    Copyright <2020> <Uri Herrera <uri_herrera@nxos.org>>"
		echo "    Copyright <2020> <Luis Lavaire <luis_lavaire@nxos.org>>\n "
		echo "Made with ♥ by Nitrux Latinoamericana S.C.\n "
		exit

	;;

esac


# -- Probe for PNX root existence.

test -d $PNX_ROOT ||
	_e "${0##*/} has not been initialized. Please run: sudo ${0##*/} --initialize\nExiting...\n "


# -- By default use Pacman if no flag is specified.

	pacman "$@"


# -- Integrate .desktop files from pnx directory into the user's directory after installing a program with Pacman.

# for dot_d in $(pacman -r $PNX_ROOT -Qql | grep '\.desktop'); do
# 	ln -sf $PNX_ROOT/$dot_d $HOME/.local/share/applications
# done

exit 0
